# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{skeleti}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jean-Philippe Boily"]
  s.date = %q{2011-04-14}
  s.description = %q{Skeleti is a little tool to generate a basic skeleton app for Titanium Mobile projects. You can also generate VCE (View, Controller and Events)}
  s.email = %q{jp@wizestudios.com}
  s.executables = ["skeleti", "ti"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/skeleti",
    "bin/ti",
    "lib/content.rb",
    "lib/file.rb",
    "lib/skeleti.rb",
    "pkg/skeleti-0.1.0.gem",
    "test/helper.rb",
    "test/test_skeleti.rb"
  ]
  s.homepage = %q{http://github.com/jipiboily/skeleti}
  s.licenses = ["MIT"]
  s.require_paths = [["lib"]]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Titanium Mobile skeleton and View Controller Events (VCE) genrator}
  s.test_files = [
    "test/helper.rb",
    "test/test_skeleti.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

